apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.50.0

  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    editable: true

  - name: VictoriaTraces
    type: tempo
    access: proxy
    url: http://victoriatraces:10428/select/tempo
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'victorialogs'
        filterByTraceID: true

  - name: VictoriaTraces-Jaeger
    type: jaeger
    access: proxy
    url: http://victoriatraces:10428/select/jaeger
    editable: true
